/*
connect to own user on PROD database  and grant to other schemas
*/
CREATE TABLE TEMPMBLOB
(ID NUMBER, 
 FILE_ID NUMBER, 
 FILENAME VARCHAR2(400), 
 BLOB_CONTENT BLOB, 
 SESSION_ID NUMBER)
/
CREATE SEQUENCE TEMPMBLOB_SEQ
  START WITH 1
  MAXVALUE 99999999999999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 2
  NOORDER;
/
CREATE OR REPLACE TRIGGER TEMPMBLOB_BI
 BEFORE INSERT
 ON TEMPMBLOB
 FOR EACH ROW
BEGIN
    ---Seq
    Select TEMPMBLOB_SEQ.NEXTVAL Into :NEW.ID From Dual;  
    ---
END;
/